# Generated by Django 4.0.2 on 2022-03-01 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=50)),
                ('AddDate', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='category_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50)),
                ('AddDate', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category_list',
            },
        ),
        migrations.CreateModel(
            name='VehicalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Name', models.CharField(max_length=50)),
                ('Type_Image', models.ImageField(upload_to='type_img')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'VehicalType',
            },
        ),
        migrations.CreateModel(
            name='vehical_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variant_Name', models.CharField(max_length=50)),
                ('Fuel_Type', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric')], max_length=10)),
                ('Seat_Capacity', models.IntegerField()),
                ('Variant_Photo', models.ImageField(upload_to='Variant_img')),
                ('Air_Condition', models.BooleanField(default=False)),
                ('Power_Steering', models.BooleanField(default=False)),
                ('Air_Bags', models.BooleanField(default=False)),
                ('Power_Windows', models.BooleanField(default=False)),
                ('Music_System', models.BooleanField(default=False)),
                ('GPS_Location', models.BooleanField(default=False)),
                ('AddDate', models.DateTimeField(auto_now_add=True)),
                ('Brand_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brand')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Vahical_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.vehicaltype')),
                ('Vahical_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.category_list')),
            ],
        ),
        migrations.CreateModel(
            name='Vehical_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddDate', models.DateTimeField(auto_now_add=True)),
                ('Vehical_Number', models.CharField(max_length=10)),
                ('Model_Year', models.IntegerField()),
                ('KM_reading', models.BigIntegerField()),
                ('Vehical_Orignal_img', models.ImageField(upload_to='Vehical_Orignal_img')),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
                ('Owner_Driving_Licence', models.FileField(upload_to='Owner_Driving_Licence')),
                ('RCBOOK', models.FileField(upload_to='RCBOOK')),
                ('Prize', models.BigIntegerField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehical_Variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.vehical_variant')),
            ],
        ),
        migrations.AddField(
            model_name='category_list',
            name='Vehical_TypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.vehicaltype'),
        ),
    ]
