# Generated by Django 4.0.2 on 2022-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehical_registration',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Use', 'In Use')], default='Pending', max_length=50),
        ),
    ]
