# Generated by Django 4.0.2 on 2022-03-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_vehical_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehical_registration',
            name='Vahical_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.vehicaltype'),
        ),
    ]
