# Generated by Django 4.0.2 on 2022-03-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='State',
            field=models.CharField(choices=[('ahmedabad', 'ahmedabad'), ('Rajkot', 'Rajkot'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('hyderabad', 'hyderabad'), ('Goa', 'Goa'), ('vadodara', 'vadodara')], max_length=20),
        ),
    ]
