# Generated by Django 4.0.2 on 2022-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicalrequest',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available')], default='Pending', max_length=50),
        ),
    ]
