# Generated by Django 4.0.2 on 2022-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_vehicalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicalrequest',
            name='Addhar_img',
            field=models.ImageField(default='User_Addhar_img/img.pdf', upload_to='User_Addhar_img'),
            preserve_default=False,
        ),
    ]
