# Generated by Django 4.0.2 on 2022-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_vehicalrequest_addhar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicalrequest',
            name='Total_Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
